# Generated by Django 5.2 on 2026-03-09 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("herbs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("inbound", "入库"),
                            ("outbound", "出库"),
                            ("check", "盘点"),
                        ],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="变更数量"
                    ),
                ),
                (
                    "before_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="变更前库存"
                    ),
                ),
                (
                    "after_quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="变更后库存"
                    ),
                ),
                (
                    "business_no",
                    models.CharField(blank=True, max_length=50, verbose_name="业务单号"),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "herb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_records",
                        to="herbs.herb",
                        verbose_name="药材",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存流水",
                "verbose_name_plural": "库存流水",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["record_type"], name="inventory_i_record__a55462_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="inventory_i_created_6087cb_idx"
                    ),
                    models.Index(
                        fields=["herb", "created_at"],
                        name="inventory_i_herb_id_0ba744_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InventoryStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="当前库存"
                    ),
                ),
                (
                    "safe_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="安全库存"
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="g", max_length=20, verbose_name="单位"),
                ),
                (
                    "warehouse_location",
                    models.CharField(blank=True, max_length=100, verbose_name="仓位"),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[("normal", "安全"), ("low", "低库存"), ("empty", "缺货")],
                        default="normal",
                        max_length=20,
                        verbose_name="库存状态",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "herb",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="herbs.herb",
                        verbose_name="药材",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存",
                "verbose_name_plural": "库存",
                "ordering": ["herb__herb_code"],
                "indexes": [
                    models.Index(
                        fields=["stock_status"], name="inventory_i_stock_s_e8365f_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="inventory_i_updated_cb053e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InventoryWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warning_type",
                    models.CharField(
                        choices=[("shortage", "库存不足")],
                        default="shortage",
                        max_length=20,
                        verbose_name="预警类型",
                    ),
                ),
                (
                    "current_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="当前库存"
                    ),
                ),
                (
                    "safe_quantity",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="安全库存"
                    ),
                ),
                (
                    "warning_status",
                    models.CharField(
                        choices=[("active", "生效中"), ("resolved", "已解除")],
                        default="active",
                        max_length=20,
                        verbose_name="预警状态",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="解除时间"),
                ),
                (
                    "herb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_warnings",
                        to="herbs.herb",
                        verbose_name="药材",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存预警",
                "verbose_name_plural": "库存预警",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["warning_status"], name="inventory_i_warning_b261e5_idx"
                    ),
                    models.Index(
                        fields=["generated_at"], name="inventory_i_generat_6bbf8f_idx"
                    ),
                ],
            },
        ),
    ]
