# Generated by Django 5.2 on 2026-03-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Herb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "herb_code",
                    models.CharField(max_length=50, unique=True, verbose_name="药材编号"),
                ),
                ("herb_name", models.CharField(max_length=100, verbose_name="药材名称")),
                (
                    "alias_name",
                    models.CharField(blank=True, max_length=100, verbose_name="别名"),
                ),
                ("category", models.CharField(max_length=50, verbose_name="分类")),
                (
                    "nature_taste",
                    models.CharField(blank=True, max_length=100, verbose_name="性味"),
                ),
                (
                    "meridian_tropism",
                    models.CharField(blank=True, max_length=100, verbose_name="归经"),
                ),
                ("efficacy", models.TextField(blank=True, verbose_name="功效")),
                ("indication", models.TextField(blank=True, verbose_name="主治")),
                (
                    "origin_place",
                    models.CharField(blank=True, max_length=100, verbose_name="产地"),
                ),
                (
                    "storage_method",
                    models.CharField(blank=True, max_length=255, verbose_name="储存方式"),
                ),
                (
                    "unit",
                    models.CharField(default="g", max_length=20, verbose_name="单位"),
                ),
                (
                    "reference_price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="参考价格"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="药材描述")),
                (
                    "extra_attributes",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展属性"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "启用"), ("disabled", "停用")],
                        default="enabled",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "中药材",
                "verbose_name_plural": "中药材",
                "ordering": ["herb_code"],
                "indexes": [
                    models.Index(
                        fields=["herb_name"], name="herbs_herb_herb_na_81b000_idx"
                    ),
                    models.Index(
                        fields=["category"], name="herbs_herb_categor_5ea57e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="herbs_herb_status_6ba2b2_idx"
                    ),
                ],
            },
        ),
    ]
