# Generated by Django 5.2 on 2026-03-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("herbs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "formula_code",
                    models.CharField(max_length=50, unique=True, verbose_name="方剂编号"),
                ),
                ("formula_name", models.CharField(max_length=100, verbose_name="方剂名称")),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="来源"),
                ),
                ("efficacy", models.TextField(blank=True, verbose_name="功效")),
                ("indication", models.TextField(blank=True, verbose_name="主治")),
                ("usage_method", models.TextField(blank=True, verbose_name="用法用量")),
                ("contraindication", models.TextField(blank=True, verbose_name="禁忌说明")),
                (
                    "remark",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "启用"), ("disabled", "停用")],
                        default="enabled",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "方剂",
                "verbose_name_plural": "方剂",
                "ordering": ["formula_code"],
            },
        ),
        migrations.CreateModel(
            name="FormulaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dosage",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="剂量"
                    ),
                ),
                (
                    "dosage_unit",
                    models.CharField(default="g", max_length=20, verbose_name="剂量单位"),
                ),
                (
                    "role_in_formula",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("jun", "君"),
                            ("chen", "臣"),
                            ("zuo", "佐"),
                            ("shi", "使"),
                        ],
                        max_length=20,
                        verbose_name="君臣佐使",
                    ),
                ),
                ("sort_no", models.PositiveIntegerField(default=0, verbose_name="排序号")),
                (
                    "remark",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="formulas.formula",
                        verbose_name="方剂",
                    ),
                ),
                (
                    "herb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="formula_items",
                        to="herbs.herb",
                        verbose_name="药材",
                    ),
                ),
            ],
            options={
                "verbose_name": "方剂组成",
                "verbose_name_plural": "方剂组成",
                "ordering": ["sort_no", "id"],
            },
        ),
        migrations.AddField(
            model_name="formula",
            name="herbs",
            field=models.ManyToManyField(
                related_name="formulas", through="formulas.FormulaItem", to="herbs.herb"
            ),
        ),
        migrations.AddConstraint(
            model_name="formulaitem",
            constraint=models.UniqueConstraint(
                fields=("formula", "herb"), name="uniq_formula_herb_item"
            ),
        ),
        migrations.AddIndex(
            model_name="formula",
            index=models.Index(
                fields=["formula_name"], name="formulas_fo_formula_f4a9f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="formula",
            index=models.Index(fields=["status"], name="formulas_fo_status_924eb6_idx"),
        ),
    ]
